### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by slorber** [applitools/eyes.storybook#3]
Hi,

As this is a beta tool that I'm trying, just giving some feedback as I tried it on 2 projects.

# project 1, using older Storybook version 3.2.10

It didn't work well, I guess I might need to upgrade storybook, or my existing config is too complex for this tool? I didn't forget the eyes-setup, have rebuilt and I'm getting the following error:

> Error: Storybook object not found on window. Check window.__storybook_stories__ is set in your Storybook's config.js.

Is there a minimum storybook version recommended to assign to window object or something? If yes that could be useful to print in the code installed by eyes-setup

 # project 2: fresh CRA project with custom react-app-rewired/babel settings

It seems to work fine (at least things are sent to the SaaS server

Just, the SaaS made me feel it was not working initially because of the screenshot preview. My component under test is small and actually renders under the top left button. Maybe it would be nice to advise storybook users to center the rendering with a decorator.

![image](https://user-images.githubusercontent.com/749374/44838150-b7b5e800-ac3b-11e8-8b8f-1877007d3172.png)

# Other

I found it wasn't very clear in doc that we should build the static storybook (or use --build option) before running `eyes-storybook`

Also, it looks like the screenshot is the whole iframe, meaning any decorator change would make all component tests break. That would be nice to document and recommend decorator migration strategies.

Also, if running `eyes-storybook` multiple times on the same static build, maybe the tool could skip instead of adding a new test run on the SaaS, as the screenshots should normally be consistent across test runs on the same static build (unless cfg has changed like viewport size)

Also not sure how to setup different viewport sizes on a per-component basis. I'd like to render small components on small iframes, and big ones (like app layouts/headers/footers) on "normal iframes"

Also not sure how to take multiple screenshots of a component? for example if it animated on mount or something, can we record that?

Otherwise thanks for that tool, it will definitively be handy to me, just need to check the pricing is ok now ;)

**Comment by slorber** [comment]
Thanks for your answers

Here is my project 1 config:

```js
if (typeof window === 'object' && window.navigator && (/node\.js/i).test(window.navigator.userAgent)) {
  let addons = require('@storybook/addons').default;
  let Channel = require('@storybook/channels').default;
  addons.setChannel(new Channel({
    transport: {
      setHandler: function() {},
      send: function() {}
    }
  }));
}

import React from "react";
import { configure, addDecorator } from "@storybook/react";
import { withKnobs } from "@storybook/addon-knobs";
import backgrounds from "@storybook/addon-backgrounds";
import { withInfo } from "@storybook/addon-info";
import { setOptions } from "@storybook/addon-options";
import { boolean } from "@storybook/addon-knobs";

import "shared/styles/js/global";

import "../frontend/app_fr";

import { colors } from "shared/styles/js/vars";

import { BrowserRouter as Router } from "react-router-dom";
import { AppApolloProvider } from "app/appApollo";

const storybookLanguage = process.env.STORYBOOK_DEFAULT_LOCALE || 'fr';

require("../frontend/app_"+storybookLanguage);


addDecorator(story => {
  if (boolean("Mounted", true)) {
    return story();
  } else {
    return null;
  }
});

// See https://github.com/storybooks/storybook/pull/1592
addDecorator((story, context) => withInfo()(story)(context));

// Required for components using links inside storybook
addDecorator(story => <Router>{story()}</Router>);

// Required for some components
addDecorator(story => <AppApolloProvider>{story()}</AppApolloProvider>);

addDecorator(story => (
  <div
    style={{
      width: "100%",
      minHeight: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    }}
  >
    <div
      style={{
        margin: 20,
        padding: 10,
        border: "dashed black thin",
        overflow: "hidden",
      }}
    >
      <div
        style={{
          //overflow: 'hidden', // We want to see the shadows
        }}
      >
        {story()}
      </div>
    </div>
  </div>
));

addDecorator(withKnobs);

// this color is not very beautiful but it's unused in the whole app so it does not conflict with existing app colors
const defaultBackgroundColor = {
  name: "default",
  value: "#f5f5ef",
  default: true
};

const otherBbackgroundColors = Object.keys(colors).map(color => ({
  name: color,
  value: colors[color],
  default: false,
}));

addDecorator(backgrounds([defaultBackgroundColor].concat(otherBbackgroundColors)));

// Option defaults:
setOptions({
  /**
   * name to display in the top left corner
   * @type {String}
   */
  name: "xxx",
  /**
   * URL for name in top left corner to link to
   * @type {String}
   */
  //url: '#',
  /**
   * show story component as full screen
   * @type {Boolean}
   */
  //goFullScreen: false,
  /**
   * display left panel that shows a list of stories
   * @type {Boolean}
   */
  //showLeftPanel: true,
  /**
   * display horizontal panel that displays addon configurations
   * @type {Boolean}
   */
  //showDownPanel: true,
  /**
   * display floating search box to search through stories
   * @type {Boolean}
   */
  //showSearchBox: false,
  /**
   * show horizontal addons panel as a vertical panel on the right
   * @type {Boolean}
   */
  downPanelInRight: true,
  /**
   * sorts stories
   * @type {Boolean}
   */
  //sortStoriesByKind: true,
  /**
   * regex for finding the hierarchy separator
   * @example:
   *   null - turn off hierarchy
   *   /\// - split by `/`
   *   /\./ - split by `.`
   *   /\/|\./ - split by `/` or `.`
   * @type {Regex}
   */
  //hierarchySeparator: null,
});

const req = require.context("../frontend", true, /.stories.js$/);

configure(() => {
  req.keys().forEach(filename => req(filename));
}, module);


if (typeof window === 'object') {
  window.__storybook_stories__ = require('@storybook/react').getStorybook();
}
```

> It is not possible right now, you can set small, normal and big viewport sizes and test all components on them. We perform this actions remotely, so it should not change your performance.

So you mean you upload the static build and the screenshots are made on your cloud infrastructure?

**Comment by amitzur** [comment]
Just to let you know, we will be releasing a new beta in about 1 week or 2, which will work a bit differently:

There will not be a setup step, and no need to build the storybook.
You will be able to provide a URL to a working storybook (not just localhost), or specify that you want to launch the storybook server for the test duration.

**Comment by danielputerman** [comment]
Hi @slorber, the new version of Eyes.Storybook SDK is now in beta :)
The documentation for beta can be found here:
https://www.npmjs.com/package/@applitools/eyes.storybook/v/2.0.12

Note:
The NPM package is the same as the existing, but with a "beta" flag, so install it with:
npm install @applitools/eyes.storybook@beta

The GitHub repo is currently https://github.com/applitools/eyes.storybook2. This repo will be renamed "eyes.storybook-legacy" or something similar.

Please see the docs for more breaking changes
